import json
import asyncio
from uuid import uuid4
from curl_cffi import requests
from ...core.config import config
from .proof_of_work import get_pow_token

# Constants
SENTINEL_REQ_URL = "https://chatgpt.com/backend-api/sentinel/req"
DEFAULT_FLOW = 'sora_create_task'

def generate_id():
    return str(uuid4())

def generate_payload(data, flow):
    data['id'] = generate_id()
    data['flow'] = flow
    return json.dumps(data)

async def fetch_requirements(session, flow, pow_token):
    max_retries = 3
    for attempt in range(max_retries):
        try:
            # Assuming POST request primarily
            response = await session.post(
                url=SENTINEL_REQ_URL,
                data=generate_payload({'p': pow_token}, flow),
                headers={"Content-Type": "application/json"}
            )
            
            # Check status
            if response.status_code == 200:
                result = response.json()
                return result, True
            else:
               # Simple retry logic for non-200
               if attempt >= max_retries -1:
                   return generate_payload({'e': f"HTTP {response.status_code}"}, flow), False
        
        except Exception as err:
            if attempt >= max_retries - 1:
                return generate_payload({'e': str(err)}, flow), False
            await asyncio.sleep(1) # Backoff slightly

    return None, False

async def refresh_token_async(flow=DEFAULT_FLOW, proxy=None):
    """
    Async version of token refresh. 
    Runs CPU-intensive PoW in a separate thread.
    """
    async with requests.AsyncSession(impersonate=config.impersonate_preset, proxy=proxy) as session:
        # Extract the User-Agent generated by curl_cffi
        user_agent = session.headers.get("User-Agent")
        
        # Run PoW in thread pool using the extracted UA
        pow_token = await asyncio.to_thread(get_pow_token, user_agent)
        
        # Use the SAME session to fetch requirements
        response, success = await fetch_requirements(session, flow, pow_token)
        if not success:
            return response

    try:
        payload = generate_payload({
            'p': pow_token,
            't': response.get("turnstile", {}).get('dx', ""),
            'c': response.get('token')
        }, flow)
        return payload
    except Exception as err:
        failure = generate_payload({'e': str(err), 'p': pow_token}, flow)
        return failure

def get_sentinel_token_sync(flow=DEFAULT_FLOW):
    """
    Synchronous wrapper if needed (blocking).
    """
    return asyncio.run(refresh_token_async(flow))

if __name__ == "__main__":
    # Test
    print(get_sentinel_token_sync())
